In [30]:
import pandas as pd
import numpy as np

model_dir = 'storage/MiniGrid-ThreeDoor-v0/aQL/lr0.10_discount0.90_eps0.80'
log = pd.read_csv(model_dir + '/log.csv', names = ['episodes', 'completed', 'reward', 'steps', 'seed'])

In [35]:
## Compute number of wins per seeds run
data_dict = {'wins':[], 'rewards':[], 'steps':[]}
episodes = np.sort(list(set(log['episodes'])))
print(episodes)
for i in episodes:
    print('Number of wins in %d episodes:'%i)
    n = len(log[log['episodes'] == i])
    wins = np.sum(log[log['episodes'] == i]['completed'])
    print('%d/%d'%(wins,n))
    data_dict['wins'].append('%d/%d'%(wins,n))
    

[ 10  20  30  40  50  60  70  80  90 100]
Number of wins in 10 episodes:
5/10
Number of wins in 20 episodes:
10/10
Number of wins in 30 episodes:
10/10
Number of wins in 40 episodes:
10/10
Number of wins in 50 episodes:
10/10
Number of wins in 60 episodes:
10/10
Number of wins in 70 episodes:
10/10
Number of wins in 80 episodes:
10/10
Number of wins in 90 episodes:
10/10
Number of wins in 100 episodes:
10/10


In [36]:
## Compute average reward

episodes = np.sort(list(set(log['episodes'])))
print(episodes)
for i in episodes:
    print('Average reward in %d episodes:'%i)
    rewards = log[log['episodes'] == i][log['completed'] == 1]['reward']
    print(np.average(rewards))
    data_dict['rewards'].append(np.average(rewards))


[ 10  20  30  40  50  60  70  80  90 100]
Average reward in 10 episodes:
14.0
Average reward in 20 episodes:
14.0
Average reward in 30 episodes:
14.0
Average reward in 40 episodes:
14.0
Average reward in 50 episodes:
14.0
Average reward in 60 episodes:
14.0
Average reward in 70 episodes:
14.0
Average reward in 80 episodes:
14.0
Average reward in 90 episodes:
14.0
Average reward in 100 episodes:
14.0


/Users/baek/.local/lib/python3.7/site-packages/ipykernel_launcher.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  import sys


In [37]:
## Compute average steps

episodes = np.sort(list(set(log['episodes'])))
print(episodes)
for i in episodes:
    print('Average steps in %d episodes:'%i)
    steps = log[log['episodes'] == i][log['completed'] == 1]['steps']
    print(np.average(steps))
    data_dict['steps'].append(np.average(steps))


[ 10  20  30  40  50  60  70  80  90 100]
Average steps in 10 episodes:
127.0
Average steps in 20 episodes:
24.0
Average steps in 30 episodes:
24.0
Average steps in 40 episodes:
24.0
Average steps in 50 episodes:
24.0
Average steps in 60 episodes:
24.0
Average steps in 70 episodes:
24.0
Average steps in 80 episodes:
26.8
Average steps in 90 episodes:
24.0
Average steps in 100 episodes:
26.8


/Users/baek/.local/lib/python3.7/site-packages/ipykernel_launcher.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  import sys


In [38]:
##save results
df = pd.DataFrame.from_dict(data_dict, orient="index")
df.to_csv("data.csv")
