In [6]:
import pandas as pd
import numpy as np
model_dir = 'storage/MiniGrid-FourDoor-v0/1000/aQL/lr0.10_discount0.90_eps0.80'
log = pd.read_csv(model_dir + '/log.csv', names = ['episodes', 'completed', 'reward', 'steps', 'seed'])

In [7]:
## Compute number of wins per seeds run
data_dict = {'episodes':[],'wins':[], 'rewards':[], 'steps':[]}
episodes = np.sort(list(set(log['episodes'])))
data_dict['episodes'] = episodes
print(episodes)
for i in episodes:
    print('Number of wins in %d episodes:'%i)
    n = len(log[log['episodes'] == i])
    wins = np.sum(log[log['episodes'] == i]['completed'])
    print('%d/%d'%(wins,n))
    data_dict['wins'].append('%d.00/%d.00'%(wins,n))
    

[ 200  400  600  800 1000 1200 1400 1600 1800 2000]
Number of wins in 200 episodes:
10/10
Number of wins in 400 episodes:
10/10
Number of wins in 600 episodes:
10/10
Number of wins in 800 episodes:
10/10
Number of wins in 1000 episodes:
10/10
Number of wins in 1200 episodes:
10/10
Number of wins in 1400 episodes:
10/10
Number of wins in 1600 episodes:
10/10
Number of wins in 1800 episodes:
10/10
Number of wins in 2000 episodes:
10/10


In [8]:
## Compute average reward

episodes = np.sort(list(set(log['episodes'])))
print(episodes)
for i in episodes:
    print('Average reward in %d episodes:'%i)
    rewards = log[log['episodes'] == i][log['completed'] == 1]['reward']
    print(np.average(rewards))
    data_dict['rewards'].append(np.average(rewards))


[ 200  400  600  800 1000 1200 1400 1600 1800 2000]
Average reward in 200 episodes:
1011.0
Average reward in 400 episodes:
1010.4
Average reward in 600 episodes:
1009.2
Average reward in 800 episodes:
1009.2
Average reward in 1000 episodes:
1006.6
Average reward in 1200 episodes:
1005.8
Average reward in 1400 episodes:
1005.6
Average reward in 1600 episodes:
1005.4
Average reward in 1800 episodes:
1005.2
Average reward in 2000 episodes:
1005.0


/Users/baek/.local/lib/python3.7/site-packages/ipykernel_launcher.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  import sys


In [9]:
## Compute average steps
episodes = np.sort(list(set(log['episodes'])))
print(episodes)
for i in episodes:
    print('Average steps in %d episodes:'%i)
    steps = log[log['episodes'] == i][log['completed'] == 1]['steps']
    print(np.average(steps))
    data_dict['steps'].append(np.average(steps))


[ 200  400  600  800 1000 1200 1400 1600 1800 2000]
Average steps in 200 episodes:
22.7
Average steps in 400 episodes:
21.6
Average steps in 600 episodes:
19.0
Average steps in 800 episodes:
19.4
Average steps in 1000 episodes:
14.9
Average steps in 1200 episodes:
13.7
Average steps in 1400 episodes:
12.8
Average steps in 1600 episodes:
12.7
Average steps in 1800 episodes:
12.6
Average steps in 2000 episodes:
12.5


/Users/baek/.local/lib/python3.7/site-packages/ipykernel_launcher.py:6: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  


In [11]:
##save results
df = pd.DataFrame.from_dict(data_dict)
df.to_csv("data.csv")
